### ISSUE TITLE
Sensu overrides config files

### ISSUE THREAD

**Issue by zoell** [sstarcher/docker-sensu#11]
Hi,

When I restart one of the containers (I am currently experimenting with the client), it overrides the config files mapped to my host when it starts up. But I would like to make changes to this config.

How to do that?

**Comment by sstarcher** [comment]
Could you give me an example of one of your configuration files and what it's doing to change them.  The only thing that it should do on startup is insert any environment variables into templated fields.

**Comment by zoell** [comment]
I am just using the compose file from here:
https://hub.docker.com/r/sstarcher/sensu/

And added a volume option to map client config file to host:

client:
  image: sstarcher/sensu
  command: client
  volumes:
    - /sensu/client/config:/etc/sensu/conf.d
  environment:
    CLIENT_NAME: alarmclient
    RUNTIME_INSTALL: sstarcher/aws sstarcher/consul
  links:
    - rabbitmq
  ports:
    - '10000:3030'

So if I go to /sensu/client/config and modify the config file, after restarting the container it restores the original file.

And this is the config file:
{
  "client": {
    "socket": {
      "bind": "127.0.0.0"
    },
    "name": "alarmclient",
    "address": "<no value>",
    "subscriptions": [
......
        "all"
......
        ,"default"
......
    ],
    "keepalive": {
      "handler": "default"
    }
  }
}

**Comment by sstarcher** [comment]
@zoell any reason you don't edit the file directly on the host?  Also what is the file extension of the file on your host?

**Comment by zoell** [comment]
It's client.json.
I don't like to go to the container end edit the config there, as relaunching the container will erase all my settings. So I always map config files to the host, edit and backup from there.

**Comment by sstarcher** [comment]
Ok I'm seeing the confusion.

The docker container has it's own config file located at /etc/sensu/config.json, but you're mounting your directory to /etc/sensu/conf.d

So you actually have 2 client.json files located at
- /etc/sensu/config.json
- /etc/sensu/conf.d/client.json

If you don't want to use the generated file you can overwrite the config.json by changing your volumes

```
volumes:
  - /sensu/client/config/client.json:/etc/sensu/config.json
```

or by telling the container the location of your client file

```
environment:
  CONFIG_FILE: /etc/sensu/conf.d/client.json
```

**Comment by zoell** [comment]
I just mapped the file to /etc/sensu/config.json but it is still overwriting it with the original one. Even if I set it to an other path via the CONFIG_FILE variable, it is overwritten :(

**Comment by zoell** [comment]
It seems that it overwrites the IP address and it tries to bind to 127.0.0.0. Just wanted to change it to 0.0.0.0 because this way I can not reach it outside of the container even if I expose that port.

**Comment by zoell** [comment]
Still not working. I tried both of your suggestion, and added a port property to the json file but it is still overwrites with the original file.

**Comment by sstarcher** [comment]
`The below message was in response to a now edited message`

@zoell what I said above should address the "overwriting"  It's not overwriting your file your looking at the wrong file.  You have 2 separate configuration files.

If all you want to do is change the BIND address you can pass in the environment value of `CLIENT_BIND`

**Comment by sstarcher** [comment]
@zoell paste the content of  /etc/sensu/conf.d/client.json and /etc/sensu/config.json

**Comment by zoell** [comment]
It worked with the CLIENT_BIND. Thanks!

**Comment by sstarcher** [comment]
@zoell sorry ignore my comment about as it will overwrite the file

```
volumes:
  - /sensu/client/config/client.json:/etc/sensu/config.json
```
