### ISSUE TITLE
Plugins don't appear to be installed

### ISSUE THREAD

**Issue by tomwadeson** [sstarcher/docker-sensu#23]
`docker-compose logs client` output:

```
client_1    | Downloading    sensu-plugins/http:master
client_1    | Building   sensu-plugins/http:master
client_1    | Installing     sensu-plugins/http:master
client_1    | Finished   sensu-plugins/http:master
```

However, when I: `docker exec -it xxx_client_1 bash` and `ls /etc/sensu/plugins`, there's nothing there.

**Comment by sstarcher** [comment]
@tomwadeson is this master of alpine branch?

**Comment by sstarcher** [comment]
@tomwadeson on the master branch which would be `sstarcher/sensu:latest` on docker.io
The plugins will be installed into the embedded ruby

```
/opt/sensu/embedded/bin/check-http.rb
```
