### ISSUE TITLE
Fail to start with the example

### ISSUE THREAD

**Issue by benjah1** [sstarcher/docker-sensu#27]
Fail to start with the example `docker-compose.yml` file.

The error is 

``` shell
Starting sensu_api_1
Attaching to sensu_api_1
api_1       | sed: no input files
sensu_api_1 exited with code 4
```

The problem seem to be in the [/bin/start](https://github.com/sstarcher/docker-sensu/blob/master/bin/start#L49) file, line 49 to 51

Since isn't `*.rb` file in `/opt/sensu/embedded/bin/`.

**Comment by sstarcher** [comment]
I believe this is fixed via - https://github.com/sstarcher/docker-sensu/commit/c1b87cb7eba1ac822afc64c60403437c2c92a91d
