### ISSUE TITLE
Docker Hub Failed Build

### ISSUE THREAD

**Issue by schodemeiss** [sstarcher/docker-sensu#31]
Looks like the Docker build of this repo failed a few weeks back: https://hub.docker.com/r/sstarcher/sensu/builds/bebvh7em4nnbf7qeagg3fqh/

You could always link your builds with "Debian" - so it'll get rebuilt whenever Debian pushes out a change. That'll ensure you're repo gets built regularly and stops these random fails from being a problem as they'll no-doubt get retried before too long.

Perhaps you can repush and update Sensu to version 0.26.5 whilst we're there?

**Comment by sstarcher** [comment]
Thanks, I tagged both 0.26.5 and 0.26.4 along with linking it to the debian build.
