### ISSUE TITLE
Server defaulting to rabbitmq

### ISSUE THREAD

**Issue by absolutejam** [sstarcher/docker-sensu#42]
Hi,

First of all, great work Dockerising Sensu in such a friendly & useful way.

I seem to be experiencing an issue wherein the server container is not correctly picking up the transport type, either from ENV vars or from the config.

If I `docker exec -it sensu_server_1 bash` and query the env, I get the following:
```
root@ccb88ba37781:/# env | grep TRANSPORT
TRANSPORT_NAME=redis
```

And if I cat the `/etc/sensu/conf.d/transport.json`, I can see the following config (Host mount):
```
root@ccb88ba37781:/# cat /etc/sensu/conf.d/transport.json 
{
    "transport": {
      "name": "redis",
      "reconnect_on_error": true
    } 
}
```

Yet when I run `sensu-server -P`, it always returns:
```
root@ccb88ba37781:/# sensu-server -P
{"timestamp":"2017-04-14T21:49:02.749351+0000","level":"warn","message":"outputting compiled configuration and exiting"}
{
  "client":{},
  "sensu":{
    "spawn":{
      "limit":12
    }
  },
  "transport":{
    "name":"rabbitmq",
    "reconnect_on_error":true
  },
  "checks":{},
  "filters":{},
  "mutators":{},
  "handlers":{},
  "extensions":{}
}
```

This means that my checks aren't getting scheduled! Any ideas?

Thanks.

**Comment by absolutejam** [comment]
Looks like it was PEBCAK issue. Thanks again for your work Dockerising this!

**Comment by sstarcher** [comment]
@absolutejam glad you got it fixed I had missed your message.
