### ISSUE TITLE
Handling sensu-install without build-essentials

### ISSUE THREAD

**Issue by absolutejam** [sstarcher/docker-sensu#44]
Hey again,

The image doesn't container `build-essentials` so I can't compile ruby gems (Eg. `sensu-install -p mailer`). How are you currently handling this?

I threw up a container that is based on your image and has `build-essentials` installed, then used this to generate the sensu files (handlers, plugins, etc.) & gems, but it's a bind to copy these over to the different folders on my `sensu_server` container.

I guess I could just build on top of your image and add `build-essentials` :man_shrugging: 

Regards,
James.

**Comment by absolutejam** [comment]
Hm, looks like I missed the `RUNTIME_INSTALL` env, which builds them before removing the build tools.

I guess the only other way is to use a builder container and ship the artifacts over to the server container via. a volume. I guess I *could* overwrite the `/opt/sensu/embedded/bin` directory with this volume as both containers would be of the same sensu version.

Anyway, thanks for the amazing set of containers - Sensu should really pick up on these!

**Comment by sstarcher** [comment]
If you use `https://github.com/sstarcher/docker-sensu/blob/master/bin/install` to do the installation it install build tools and than removes it.

**Comment by sstarcher** [comment]
I'm going to close it let me know if you have any questions.
