### ISSUE TITLE
Sensu not writing to /var/log/sensu/...

### ISSUE THREAD

**Issue by absolutejam** [sstarcher/docker-sensu#45]
Sorry for another issue!

I've noticed that the containers aren't writing logs to `/var/log/sensu`, so the only way I can get some more info is to change the `LOG_LEVEL` and follow stdout.

Should this work or could this be added as an env var?

Cheers.

**Comment by sstarcher** [comment]
Docker containers normally return logs to stdout/stderr and you can use the docker log drivers to handle the logs from that point forward.
