### ISSUE TITLE
docker-compose up failing for client_1

### ISSUE THREAD

**Issue by saurabh-hirani** [sstarcher/docker-sensu#46]
Hi,

Thanks for creating this docker-sensu container. I ran docker-compose up and I got the attached error for client_1.

[sstarcher_client_1_err.txt](https://github.com/sstarcher/docker-sensu/files/1035462/sstarcher_client_1_err.txt)

Adding the snippet at which the failure occurs. 

```
client_1  | update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
client_1  | Setting up build-essential (12.1ubuntu2) ...
client_1  | Processing triggers for libc-bin (2.24-9ubuntu2) ...
client_1  | Processing triggers for sgml-base (1.29) ...
client_1  | Downloading          sstarcher/aws:master
client_1  | Downloading          sensu-plugins/mail:master
client_1  |
client_1  | gzip: stdin: not in gzip format
client_1  | tar: Child returned status 1
client_1  | tar: Error is not recoverable: exiting now
client_1  | /bin/install: line 47: cd: sensu-plugins-mail-master: No such file or directory
client_1  | Building     sensu-plugins/mail:master
```

Is there something I am missing here?

**Comment by sstarcher** [comment]
It looks like mail either never existed or was moved to mailer - https://github.com/sensu-plugins/sensu-plugins-mailer

**Comment by sstarcher** [comment]
I updated the docs, let me know if you have any additional issues.
