### ISSUE TITLE
Manage multiples datacenters with uchiwa

### ISSUE THREAD

**Issue by duylong** [sstarcher/docker-sensu#52]
Hi,

It's good if we can add multiples datacenters for uchiwa configuration :)

**Comment by sstarcher** [comment]
I'm not sure I understand the request.  Uchiwa container is in a separate repo.  If I'm not mistaken your question is directed toward the Uchiwa container which only allows you to configure a single DC.

I would recommend feeding in your own configuration file for the uchiwa configuration as it gets a good bit more difficult for a user to supply a list.

https://github.com/sstarcher/docker-uchiwa/blob/master/templates/config.json.tmpl#L2

**Comment by 030** [comment]
@duylong just run a sensu-api in each dc

**Comment by duylong** [comment]
Yes, but it is better to centralize the whole in a single interface.

**Comment by 030** [comment]
sensu has a decentralized architecture

**Comment by duylong** [comment]
Uchiwa can manage multiple sensu instances.

```Uchiwa aggregates the data of all your Sensu instances in order to offer an unified view of your infrastructure. Each instance is represented as a datacenter and can be easily filtered.```

**Comment by 030** [comment]
Yes that is why I said that one should run a sensu-api in every dc. In the uchiwa config it is possible to configure multiple datacenters.

**Comment by 030** [comment]
Example: https://github.com/030/ansible-sensu-server/blob/master/templates/uchiwa.j2

**Comment by sstarcher** [comment]
Ah @030 thanks for clearing that up.  I mistakenly assumed this was a comment on `docker-uchiwa`.  Yes, you must run multiple sensu instances to specify multiple data centers.  It makes no logical sense to have multiple datacenters in a single location.  Sensu does not support having a single sensu-api register as multiple datacenters.
