### ISSUE TITLE
1.0.0 is using end of life Ubuntu Zesty

### ISSUE THREAD

**Issue by arudge** [sstarcher/docker-sensu#65]
The 1.0.0 release of this repo is now end of life -> https://wiki.ubuntu.com/Releases

Thoughts on cutting a new 2.0.0 release based on master?

This will let users lock to a version instead of commit hash or 'latest'.

**Comment by sstarcher** [comment]
As of 7 days ago this repo was updated to be based from 
```ruby:2.4-slim-stretch```

I can cut a tag for 1.2.x if you like, but I'm not sure what you are mentioning about 2.0.0

**Comment by sstarcher** [comment]
Tagged 1.2 and 1.2.0 - https://hub.docker.com/r/sstarcher/sensu/tags/

**Comment by arudge** [comment]
Awesome thanks!
