### ISSUE TITLE
Using sensu-client to check the machine where container is running

### ISSUE THREAD

**Issue by gianfrancocianchetti** [sstarcher/docker-sensu#77]
Is the docker sensu-client designed to perform checks in the machine where the container is running?

For example process checks are returning just results relative to processes running within the container.

How can we manage that?

**Comment by jwarnier** [comment]
Honestly, what would be the goal to monitor processes inside a container where only the monitoring tool is running?
Of course, it is meant to monitor its host, or other external items (host, processes/container on the host, remote checks, ...).

**Comment by sstarcher** [comment]
@gianfrancocianchetti it's setup to allow you to mount the proc of the host so you can monitor the host OS.  Please see `Define volumes to access host`

https://github.com/sstarcher/docker-sensu#configuration
